### ISSUE TITLE
a plugin's init callback should either be mandatory or not transported

### ISSUE THREAD

**Issue by nherment** [rjrodger/seneca#110]
Some of the plugins do not declare the seneca.add({init: plugin}). That causes problem when the plugin is running in a separate process as the client.

The following code reproduces the issue (seneca@0.6.1) :
```
var senecaClient = require('seneca')()
senecaClient.client({
   type: 'web',
   host: 'localhost',
   port: 10001
})

senecaClient.use(function(options) {
  var pluginName = 'foobar'

  // uncommenting the following works around the problem:
  //this.add({init: pluginName}, function(args, cb) {
  //  cb()
  //})

  return {
    name: pluginName
  }
})


var senecaServer = require('seneca')()
senecaServer.listen({
   type: 'web',
   host: '0.0.0.0',
   port: 10001
})
```
It would be nice to either:
- do not transport any of the *init* commands and keep them local
- crash the load of plugins which do not declare the *init* command

**Comment by rjrodger** [comment]
it's a bug; role:seneca patterns should never be transported
and init should be a role:seneca pattern
(definition of init function should be made easier, perhaps allow an init prop in plugin meta info)
