### ISSUE TITLE
args.fatal$:true is passed when it is not expected. Causes app to crash

### ISSUE THREAD

**Issue by nherment** [rjrodger/seneca#112]
In a module, when the microservices use the module level seneca, the subsequent 'act' are executed with fatal$: true.

See the following code:

```
var seneca = require('seneca')()

seneca.use(function(options) {
  var moduleLevelSeneca = this
  
  moduleLevelSeneca.add({role: 'entity', cmd: 'save'}, function(args, cb) {

    // using the module level instance causes the seneca.fixedargs.fatal$ to be true
    moduleLevelSeneca.act({role: 'check', cmd: 'fatal'}, cb)

    // uncommenting this line would cause seneca.fixedargs.fatal$ to be falsy (as expected)
    //this.act({role: 'check', cmd: 'fatal'}, cb)
    
  })

  
  moduleLevelSeneca.add({role: 'check', cmd: 'fatal'}, function(args, cb) {
    if(args.fatal$) {
      throw new Error('fatal$ should be falsy')
    } else {
      cb()
    }
  })
})


seneca.make('foo').save$()

```

**Comment by nherment** [comment]
fyi @rjrodger

**Comment by nherment** [comment]
@rjrodger this is a show-stopper for us as many of our tests expect and validate errors returned by the app.
It seems there is no way to get a 'clean' seneca instance in a module.
Also, seneca.delegate() does not override but 'augments' an existing seneca instance's fixed args.

**Comment by rjrodger** [comment]
This is actual correct behaviour. Plugin init errors are fatal. They can occur during definition or the init action.

Action definitions should always use the context seneca - `this`.

In 0.6.1 you can work around this with the option debug.undead = true, which prevents fatal errors from shutting down the process.

**Comment by nherment** [comment]
@rjrodger thanks for the answer on this.

It makes sense that actions should use the context seneca.
I assume ``debug.undead`` does not prevent these fatal errors to be printed so we can't use them as they are part of the app.

If I use the contextual seneca, I have a problem where some plugins need to override some fixed args but it isn't allowed either:

```
var seneca = require('seneca')()
seneca.add({cmd:'printFoo'}, function(args, cb) {
  console.log('***', args.foo)
  cb()
})

var senecaFixedArgs = seneca.delegate({foo: 'original'})
var senecaFixedArgsOverridden = senecaFixedArgs.delegate({foo: 'overriden'})

// this will print "*** original" and i would expect it to print "*** overridden"
senecaFixedArgsOverridden.act({cmd: 'printFoo'})
```

**Comment by nherment** [comment]
btw, I believe this is due to the order of the _.extend() args here: https://github.com/rjrodger/seneca/blob/e921421d230699628370443ef755949022c4fa00/seneca.js#L1780

**Comment by rjrodger** [comment]
we need a "get out of jail" for fixedargs

**Comment by nherment** [comment]
oops

**Comment by idosh** [comment]
is there any solution?

**Comment by nherment** [comment]
@idosh, you can use seneca.root.delegate({}) and it will be free of default fixed args.

**Comment by cmfatih** [comment]
@rjrodger @nherment : any update on this?

**Comment by nherment** [comment]
@cmfatih not sure what you mean ? The thread says it all, maybe not very clearly.

``seneca.root.delegate({})`` should be your joker. Are you able to remove the fixed args by using it ?

**Comment by cmfatih** [comment]
@nherment : I thought it was a temp solution. Thanks :-)

**Comment by brkattk** [comment]
I came across this same issue. Basically, if you're using the module's `this`, you might want to change it to `this.root` in order to be able to override `fatal$: false`.

```js
'use strict';

var Promise = require('bluebird');

module.exports = function() {
  var seneca = this.root;
  var act = Promise.promisify(seneca.act, seneca);

  function agentStuff( args, done ) {
    return act('role:serviceA,cmd:doStuff', { key: args.key, secret: args.secret })
      .reduce(function(counts, item) {
        return act('role:serviceB,cmd:doOtherStuff,fatal$:false', item)
          .then(function() {
            counts.good += 1;
            counts.total += 1;
            return counts;
          })
          .catch(function(err) {
            counts.bad += 1;
            counts.total += 1;
            counts.errors.push(err);
            return counts;
          });
      }, { name: args.name, good: 0, bad: 0, total: 0, errors: [] })
      .nodeify(done);
  }

  seneca.add({role: 'my-service', cmd: 'my-command', agent: 'my-agent'}, agentStuff);

  return 'name';
};
```

**Comment by rjrodger** [comment]
The plugin module seneca instance, provided by `this` is only for action pattern definition - plugin definition is synchronous.

Unfortunately earlier versions of Seneca, and earlier versions of the examples, did not observe this properly. Also `seneca.pin` has proven problematic as it is usually constructed from the module `this`.

In summary, module `this` is only for calling `seneca.add`. Actions needs for plugin initialization should happen in the init action.
