### ISSUE TITLE
respond with string doesn't work (sometimes)

### ISSUE THREAD

**Issue by boxxxie** [rjrodger/seneca#114]
```javascript
seneca.add({whatever:whatever}, function(err, respond){ respond(null, "success"); });
```
when i curl this, works fine.
when i do 
```
seneca.act({whatever:whatever},function(err, resp){console.log(err, resp);});
```
i get print outs of  ```null null```

**Comment by rjrodger** [comment]
The only valid responses are objects. Anything else should trigger an error.

**Comment by rjrodger** [comment]
in master (will be 0.6.2), you can use option strict:{result:false} to allow non object results

**Comment by AdrianRossouw** [comment]
this is kind of inconvenient for plugins, who aren't in control of what the seneca instances give them.
I also would kind of expect null or undefined to pass through at least.

I ended up having to wrap an elasticsearch.js callback in an extra function to deal with this.

**Comment by kurzgame** [comment]
Seneca needs objects? - No problem, I thought.
In my task I have to respond with number value, so I wrote:
`new Number(MY_VALUE);`
but it anyway shows me an error message.
It's kind of strange behaviour since `new Number` is Object!
