### ISSUE TITLE
getting started needs update

### ISSUE THREAD

**Issue by pucchur** [rjrodger/seneca#120]
trying to compile sample code from seneca.js website 

var seneca = require('seneca')()
seneca.add({role:'math', cmd:'product'},function(args,callback)
{
var product = args.left * args.right
callback(null,{answer:product})
})
seneca.use('transport')
var connect = require('connect')
var app = connect()
  .use( connect.json())
  .use( seneca.service())
  .listen(10171)

showing me this error
C:\microjs\server.js:10
  .use( connect.json())
                ^
TypeError: undefined is not a function
    at Object.<anonymous> (C:\microjs\server.js:10:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

am I doing something silly here?

**Comment by tigerswithguitars** [comment]
It seems the 'getting started' code is very much out of date. I don't think the `.json()` plugin for connect has been valid for a while now and on the seneca-transport plugin NPM page there is a lot more info on clients and listeners. +1 for getting this issue resolved by an update to the getting started guide though. Makes for a high barrier of entry if you can't just cut and paste the examples and have them work!

**Comment by mcdonnelldean** [comment]
@pucchur @tigerswithguitars Hi! Just to let ye know, the docs and samples are being worked on at the moment. On the docs side they are being updated to reflect the latest version and also being reworked with a focus on ease of understanding.

On the samples side, there are a number of partner examples being created to support the docs as well as ones that demonstrate common questions. 

Unfortunately I don't have an exact timeframe for these to drop. I'll ping @rjrodger early next week to finalise what goes out and when. There is a good chunk of work left to do mind but it is coming along nicely.

**Comment by pucchur** [comment]
cheers @mcdonnelldean I am really not able to proceed any further die to the error.. and @tigerswithguitars for confirming that its an error, I thought I was doing something wrong.

**Comment by mcdonnelldean** [comment]
Is there anything specific your trying to do or are you just looking to run through the samples?

**Comment by pucchur** [comment]
I am hobbyist planning to build an application to create invoices a more microservices styled architecture and deploy it on docker, so I want to play around with the seneca framework before starting to develop with it.

**Comment by iantocristian** [comment]
@pucchur the sample code is a bit outdated alright, you need to use these modules for it to work:
```
npm install connect@2.9.x
npm install seneca@0.5.x
```

**Comment by rjrodger** [comment]
renaming to reflect real issue - getting started is out of date!

**Comment by rjrodger** [comment]
updated! and rewritten!
http://senecajs.org/getting-started.html
