### ISSUE TITLE
priors matched partial patterns

### ISSUE THREAD

**Issue by rjrodger** [rjrodger/seneca#130]
priors should only match exact patterns

bug was, given patterns a:1 and a:1,b:2, then a:1 was a prior for a:1,b:2 - not correct!

**Comment by AdrianRossouw** [comment]
isn't this kind of a breaking change though ?
I'm pretty sure I am dealing with code that depends on this behaviour in seneca-elasticsearch.

The entity management defines additional events that need to be triggered for entities, and then falls back to the originally defined behavior after it has indexed the entity.
