### ISSUE TITLE
Testing an expected error thrown from a seneca action

### ISSUE THREAD

**Issue by scowling** [rjrodger/seneca#131]
Sadly, new to seneca.. and node in general, so I might be missing something here. However:

I'm trying to test a service, and create a test that is expecting an error to be generated.

I am not sure how to correctly throw an error from a seneca end point  - with the goal to test that the correct error is thrown.

Some code:

[in service]
    seneca.add('role:component,cmd:find', findComponentByName);

    function findComponentByName(args, callback){
        var componentEntity = seneca.make$('component')
        var component = componentEntity.list$(args.params.name,function(err,component){
            if(err || component.length < 1){
                console.error("Component not found:", args.params.name);
                throw ("Component not found:"+args.params.name) //<<<<how to throw here properly
            }else{
                callback(null, {component:component})
            }
        });
    }

[in test]

    describe('testing component service', function() {
    var si = seneca({log:'silent'});
    si.use('../app/services/component.service.js');
    it('test failure when trying to retrieve unknown component by name', function (done) {
        si.options({errhandler:make_errhandler(done)});
        var params = {
            name: 'ThisComponentNameDoesNotExist'
        };
        var componentResult = {};
        si.act({role: 'component', cmd: 'find'},{params:params}, function(err, result){
            assert.ok(err!=null); //<<<< how to test the error here
            done();
        });
    });
    });

**Comment by rjrodger** [comment]
In general, you should avoid throw/catch in Node.js code - it doesn't work for async code.

In this case, you want to use something like:

```
function findComponentByName(args, callback){
    var componentEntity = seneca.make$('component')
    var component = componentEntity.list$(args.params.name,function(err,component){
        if( err ) return callback( err ): // this is known as "'early return" - err goes back via callback, not throw

        // not found is not an error, just a data characteristic, so maybe do this:
        callback( null, { component:component, found:(!component || component.length<1) } )     
    });
}
```

**Comment by scowling** [comment]
Thanks - you're right, it's not an error.
Good call.

Cheers
