### ISSUE TITLE
Endless loop in seneca.act

### ISSUE THREAD

**Issue by seroukhov** [rjrodger/seneca#135]
After transition from 0.6.1 to 0.6.2 seneca.act started falling into endless loop at
    at descdata (\node_modules\seneca\lib\common.js:372:24)
    at descdata (\node_modules\seneca\lib\common.js:343:22)
   ...

**Comment by rjrodger** [comment]
@seroukhov I've removed this code from master and replaced it - could you check against master to see if the problem still exists? Thanks!

**Comment by seroukhov** [comment]
All my unit tests are passing now. It seems the issue is fixed. Thanks a lot, Richard!

BTW It seems that in 0.6.2 seneca does more rigorous validation of return values. Before I could pass objects with function references in them, but now seneca throws "should return object or array". That error message is a little misleading, since I did pass an object, just not a valid one.

**Comment by rjrodger** [comment]
@seroukhov thanks! really appreciate your help
Return values need to be plain data objects, as they may have to travel over the network.
