### ISSUE TITLE
act_error issue

### ISSUE THREAD

**Issue by iantocristian** [rjrodger/seneca#144]
We are having an issue where seneca crashes in act_error here https://github.com/rjrodger/seneca/blob/master/seneca.js#L1750 because `code` is missing... Is seneca correct in assuming that if `orig` is present on the `err` then `orig.code` must also be present and of type string?

**Comment by rjrodger** [comment]
no - needs an existence check
you're in luck, just about to release 0.6.4 with a few bug fixes, will roll this in
