### ISSUE TITLE
How to replicate behaviour of this.prior without strict.add:false

### ISSUE THREAD

**Issue by AdrianRossouw** [rjrodger/seneca#145]
I need to design a seneca plugin, and what I have in mind is going to rely on the behaviour before #130.

```javascript
var seneca = require('seneca')({ strict: { add: false }}); // breaks without the option

function called(order) {
  return function(args, done) {
    console.log(order);
    this.prior(args, done) // what do I do here to get the same behaviour?
  };
}

seneca.add('a:1', called('last'));
seneca.add('a:1,b:1,c:1', called('first'));
seneca.add('a:1,b:1', called('never'));

// Outputs: 'first' then 'last'. but not 'never'.
seneca.act('a:1,b:1,c:1', function() {});
```

Without the strict flag, only 'first' is output because this.prior would only call
another action with the exact same pattern. How do I drop down to a lower
level of specificity, from the action code?

I don't actually think the strict behaviour is correct either. I was hoping for
'first', 'never' then 'last' to be printed, because that's what .prior seems to
be used for everywhere.

I would attribute that to the context being set on the callback at 'add time',
instead of at 'act time'.

**Comment by rjrodger** [comment]
try seneca.wrap("a:1,b:1,c:*") - that _should_ work, but you'll need to test

for zeno, and thus seneca 0.7, seneca.add will support * globs, so wrap will be unnecessary, and strict.add moot

that's the theory anyway - your plugin will be a good test case for understanding this case more deeply

**Comment by AdrianRossouw** [comment]
It doesn't work, because it is ignored based on the order it is added in and the specificity of the pattern match.

```
// breaks without the add false
var seneca = require('seneca')({strict:{add:false}});

var orders = [];

function called(order) {
  return function(args, done) {
    orders.push(order);
    this.prior(args, done)
  };
}

// only works when seneca.wrap is called last
// strict.add doesn't matter here.
seneca.wrap('a:1,b:1,c:*', called('1st'));

seneca.add('a:1,b:1', called('3rd'));
seneca.add('a:1,b:1,c:1', called('2nd'));

seneca.act('a:1,b:1,c:1', function() {
  console.log(orders);
});
```

I'm busy putting together a set of tests that figures which of the combinations breaks unsuspectedly with strict.add enabled and disabled. So far it's pretty grim...

It also turns out that there's a bunch of the asynchronous tests that were not correctly handling callbacks, even from before they were moved to lab it seems. So there's going to be a lot of PR's coming this way :/
