### ISSUE TITLE
is it possible to talk to multiple processes from one client? 

### ISSUE THREAD

**Issue by timoweiss** [rjrodger/seneca#151]
We currently using hapi and have developed different plugins to separate things. But we are looking at microservices and want to use them to distribute businesslogic across processes and/or server-instances.

A simple usecase for us would be registering a new user.
[in the hapi route handler] create new user
* create new user in database
    * send confirmation mail
    * do some tracking stuff
    * send slackbot notification

All tasks after the user has been created can act concurrently. All of this work should be done in independent microservices. So each service is listening on a different port.
But *we haven't figured out how to talk to all the instances by one client*.

Are we missing something or are there convenient ways to achieve this?

Many thanks in advance!

**Comment by rjrodger** [comment]
You'll need to use a seneca-transport that can provide pub/sub for your messages - try:
https://github.com/rjrodger/seneca-beanstalk-transport or
https://github.com/rjrodger/seneca-rabbitmq-transport
@geek good use-case for a hapi example in seneca-examples :)

**Comment by geek** [comment]
@timoweiss have you had a look at https://www.npmjs.com/package/chairo yet?

I will definitely add a good example of using hapi and seneca for a similar set of services.

**Comment by timoweiss** [comment]
@rjrodger thanks, we thought that we going to need something rabbitmq.
@geek yes, we've already played around with it and we will use it. But we've already updated to hapi@9 and we will wait until "9.x.x" will be supported.

**Comment by timoweiss** [comment]
@rjrodger I was playing around with rabbitmq and beanstalk transports.
I set up a simple example like the following:
```
seneca({
    transport: {
        rabbitmq: {
            timeout: 1000
        }
    }
})
    .use('rabbitmq-transport')
    .add('role:notifications,action:schoenhier', function (message, done) {
        console.log('notificator is doing the job for schoenhier');
        done(null, message);
    })

**Comment by timoweiss** [comment]
@rjrodger I've tested both, rabbitmq and beanstalk. I set up a simple example with *two services* and *one client* and if I got it right, I need to use `pins` to announce the services I want to talk to.

```javascript
//mailerService.js
seneca()
    .use('rabbitmq-transport')
    .add('role:mailer,action:newUser', handlers.newUser) 
    .listen({type: 'rabbitmq', pin: 'role:mailer'});
```
```javascript
//notificationsService.js
seneca()
    .use('rabbitmq-transport')
    .add('role:notifications,action:newUser', handlers.newUser) 
    .listen({type: 'rabbitmq', pin: 'role:notifications'});
```
That looks good to me and is working. But if I now want to use those services in my client, I need to specify the *exact pattern* I'm going to call:
```javascript
// client.js (later done with chairo)
seneca()
    .client({type: 'rabbitmq', pin: 'role:notifications,action:newUser'})
    .client({type: 'rabbitmq', pin: 'role:mailer,action:newUser'})
    .use('rabbitmq-transport')
    .act('role:notifications,action:newUser', callbackNotification)
    .act('role:mailer,action:newUser', callbackMailer);
```

If I don't, I'm running into a timeout. I think I'm not doing it right. Maybe you guys can give me a hint? :)

Thanks for your time!

**Comment by rjrodger** [comment]
this is correct - except you can use glob matching to make things a little easier:

`.act('role:mailer,action:*', callbackMailer);` will map all matching patterns
