### ISSUE TITLE
the pin key "role" conflicts with "role" in my protocol

### ISSUE THREAD

**Issue by psnider** [rjrodger/seneca#158]
Is there a preferred or canonical way to deal with protocols (requests) that include the term 'role'?

I use "role" to indicate whether a user is is a "administrator", "user", "guest", or "invitee".

I looked through the seneca code and found that all keys ending in a '$' are removed by argpattern(),
so I cannot use "role$" in my patterns.

What do should I do? 
I don't think removing "role" is the best choice. I prefer a solution that allows me to use any normal key (without a $ sign is fine).

**Comment by psnider** [comment]
For now, I've modified input messages to follow this pattern, here for a Person data type.
The types are shown in TypeScript with: KEY_NAME: VALUE_TYPE
```typescript
interface Request {
    role: string;  // used by Seneca, not part of the API
    action: string;    // create, read, update, delete 
    person?: Person;  // the data for an entity
}
```
This way, I've changed the namespace of collisions from *fields* to *entity types*, which are much less likely to collide for me.

**Comment by raisch** [comment]
'role' is simply the idiom that seneca uses, so all calls to underlying (pre-defined) seneca actions should follow it. It's my understanding that you can use any message pattern you want, including substituting another word for 'role' _in your own messages/actions_. For example: `{using:'µservice',request:'foo',...}`

**Comment by rjrodger** [comment]
yup - there's nothing special about role - you can make up patterns you like

@psnider messages are better without schemas - Postel's law and all that - in particular this enables multi-version microservice deployments and fine-grained migrations

**Comment by psnider** [comment]
I was confused when I searched the code for *role* and found references in seneca.js, store.js, and entity.js like:
- args.role = 'entity'
- var args = _.extend({role:'entity',cmd:cmd},entargs)
- root.act('role:seneca,ready:true,gate$:true')

So I'm guessing that role is used internally just for some action patterns.

**Comment by raisch** [comment]
That's correct. 

Especially for data stores where the `[list,load,save,remove,native]$.()` interface (which calls internal methods using the `{role:'entity',cmd:'operation'}` pattern) hides them from view.

--
Rob Raisch, Internet Handyman
