### ISSUE TITLE
Why Actions in Seneca?

### ISSUE THREAD

**Issue by qnimate** [rjrodger/seneca#162]
I don't understand the real reason of introducing actions in seneca. Everything we do using actions can be done using direct functions. So what is the advantage of pattern matching then?

**Comment by rjrodger** [comment]
this approach allows you to implement microservices using the principles of pattern-matching and transport independence - no service needs to know anything about any other service, so they are fully decoupled.
See also https://www.youtube.com/watch?v=fVfWuked2qE&list=PLPhU2Tz1TddCis5MZlx1HQeK5GYJoIbu8&index=3
