### ISSUE TITLE
Seneca Upload Images

### ISSUE THREAD

**Issue by qnimate** [rjrodger/seneca#166]
I have a HTML form to upload images.

I can get the path of the image file in express. I have a action running in an another process as service. How can I send the image file to that process by calling `act` method.

The action that resides in the different process is responsible for doing something with this file.

Overall I want to know how can I transfer files between services?

Please help. Thanks.

**Comment by rjrodger** [comment]
in a word, don't :)
seneca messages are not intended for large data - instead, store the image somewhere, say s3, or a local data store, and pass a reference for the processing service
