### ISSUE TITLE
guide: how to build a store with seneca-store-test

### ISSUE THREAD

**Issue by paolochiodi** [rjrodger/seneca#186]
Hi, as part of my work in rewriting seneca-store-test I'm going to put together a brief guide on how to build a store.

However, there are a couple of things that are a bit obscure to me, and would be helpful if someone can explain me so that I can add that to the guide.

The first thing I encountered is the ceremony needed to register a store, something like:

```js
  var meta = seneca.store.init(seneca, opts, store);
  desc = meta.desc;
  seneca.add({ init: store.name, tag: meta.tag }, function (args, done) {
    setup(opts, done);
  });
```

This is common among many of the current stores, but I'm not sure why is `seneca.store.init` needed and what it actually does, what is the meta object returned, and what's the need for the "init command" registered into seneca.

I'm also wondering if we are open to change and simplify this part of the api.

cc @mcdonnelldean @geek @rjrodger

**Comment by mcdonnelldean** [comment]
@paolochiodi Can we actually move this over here: https://github.com/senecajs/senecajs.org/issues My mistake but otherwise it will get lost :D

**Comment by paolochiodi** [comment]
@mcdonnelldean no mistake, you told me about that and I forgot about it
