### ISSUE TITLE
Same code working on MAC but not working on windows

### ISSUE THREAD

**Issue by feranf** [rjrodger/seneca#192]
Hi,
I'm running the following code in MAC - works OK.
**When running it on windows 7 - the following error occurs..**
```javascript
function color() {
  this.add( 'color:red', function(args,done){
    done(null, {hex:'#FF0000'});
  })
}


var seneca = require('seneca')


seneca()
  .use(color)
  .listen({type:'tcp'})

seneca()
  .client({type:'tcp'})
  .act('color:red')

// node readme-color-tcp.js --seneca.log=plugin:transport,level:INFO --seneca.log=type:act,regex:color:red
```
* same for http transport
* firewall was disabled...

**The Error:**
2015-10-15T09:14:46.808Z s3fx6o3a4jgi/1444900486776/7384/- DEBUG        act     remote$         IN  m9bqsfq0d1ms/mj7vu98io1jj
        {color:red}     ENTRY   CLIENT  -       -       -
2015-10-15T09:14:57.946Z s3fx6o3a4jgi/1444900486776/7384/- ERROR        act     remote$         OUT     -       11135   {color:r
ed}     ENTRY   CLIENT  -       seneca: Action  failed: [TIMEOUT].      act_execute     {id:m9bqsfq0d1ms/mj7vu98io1jj,gate:false
,ungate:false,desc:,plugin:{name:remote$,tag:null},time:{start:14449004 Error: [TIMEOUT]
    at null._onTimeout (C:\seneca\node_modules\seneca\node_modules\gate-executor\gate-executor.js:95:
21)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

Thanks,

**Comment by feranf** [comment]
Discussed in https://github.com/senecajs/senecajs.org/issues/73

**Comment by thekemkid** [comment]
Okay, this works:

```
function color() {
  this.add( 'color:red', function(args,done){
    done(null, {hex:'#FF0000'});
  })
}


var seneca = require('seneca');

seneca()
  .use(color)
  .listen({type:'tcp'}) //become a server

seneca()
  .client({type:'tcp', host:"localhost"}) //become a client
  .act('color:red', console.log)
```

**Comment by mcdonnelldean** [comment]
@thekemkid can you jump back over to the original issue senecajs/senecajs.org#73
