### ISSUE TITLE
document this.prior

### ISSUE THREAD

**Issue by rjrodger** [rjrodger/seneca#28]
this.prior is key functionality!

needs to be documented with examples etc

**Comment by AdrianRossouw** [comment]
So other than #130 changing the behaviour, I believe I can explain it like this:

> Each unique pattern can only have a single action registered for it (cf. [patrun #8](https://github.com/rjrodger/patrun/issues/8). When you add another action with an existing pattern, seneca will exposed the previously registered callback to your callback as `this.prior`.

We will need to resolve the other issue, as the behaviour before 0.6.1 was that the this.prior was set to the callback of the most specifically matched action, at the time the seneca.add was called.

https://github.com/rjrodger/seneca/blob/master/test/seneca.test.js#L367-L421

**Comment by Ilyes512** [comment]
Hey,

I am both reading @rjrodger book (The Tao of Microservices) and reading through the Seneca Getting started guide when I noticed `this.prior()`. I am still new to Seneca so I thought I could find it on http://senecajs.org/api, but that was not the case. Should this not be added to the API page?
