### ISSUE TITLE
Started getting use-plugin: Could not load plugin error recently

### ISSUE THREAD

**Issue by wolfeidau** [rjrodger/seneca#64]
Did Something seems to have changed in the last month or so? 

Our app is now getting.

```
Seneca Fatal Error
==================

Message: use-plugin: Could not load plugin ./lib/store-extend; require search list: ./lib/store-extend, seneca-./lib/store-extend, ././lib/store-extend, ./seneca-./lib/store-extend.

Code: plugin_not_found
```

Any ideas on how to best sort this out?

`package.json` dependency is listed as 

```
"seneca": "~0.5.15",
```

Did something big change in a patch release?

I noticed #50 but it didn't have a lot of detail.

Cheers

**Comment by rjrodger** [comment]
can't replicate
fairly old, so closing
