### ISSUE TITLE
Mandatory parameters ?

### ISSUE THREAD

**Issue by asafyish** [rjrodger/seneca#65]
Hi,

I have the following pattern:
```
seneca.add({cmd: 'get-lists', type: 'mailchimp'}, getLists);
```
I want all the calls to seneca.act to be like:
```
seneca.act({cmd: 'get-lists', type: 'mailchimp', dc: 'us8', function() {...})
```
where 'dc' is required (but it's dynamic), if it's not supplied - throw an error without even reaching the getLists function. Is that possible ? I can check if the args are not complete and then throw an error, but that's boilerplate that I rather not duplicate.

I think it will be best if we can even use regular expressions inside 'dc', so we can just write a regexp that fits exactly what we consider as valid input.

**Comment by rjrodger** [comment]
fixed, but needs documentation, as per https://github.com/rjrodger/seneca/issues/88
