### ISSUE TITLE
unknown messages need more fine-grained control

### ISSUE THREAD

**Issue by rjrodger** [rjrodger/seneca#74]
message.unknown =
error - error log as <= 0.5.20
warn - warn log <- new default
ignore - no log

**Comment by rjrodger** [comment]
add options to handle this, acted on in api_act

**Comment by gogaman7** [comment]
Could you please give me a snippet of code that will ignore unknown messages?

I tried digging around the code, with no success.
thank you.

**Comment by rjrodger** [comment]
use the option to set the log level for unknown messages: e.g. 
`var instance = seneca( {trace:{unknown:'debug'}} )`
