### ISSUE TITLE
Shouldn't api_options() return a reference to seneca?

### ISSUE THREAD

**Issue by ErikOrjehag** [rjrodger/seneca#80]
I think the expected return value of api_options() is a reference to the seneca instance. It would make this kind of chaining possible.

```js
require('seneca')()
  .options('./dev.options.js')
  .use('nid')
  .add({ ... }, function (args, done) { ... })
  .listen();
```

Heres a [link](http://senecajs.org/doc/seneca.html#section-52) to the annotated source. Also the scope of the "so" variable is not the function, but that might be on purpose...

**Comment by rjrodger** [comment]
this needs to be documented

**Comment by rjrodger** [comment]
rock and a hard place... going to leave this API as is:

seneca.options( ... ) always returns options data object, not instance
but .use('options') does allow chaining
