### ISSUE TITLE
Possible to use other languages over Redis?

### ISSUE THREAD

**Issue by henry74** [rjrodger/seneca#81]
I'm interested in using other languages like ruby as a microservice in addition to nodejs.  Is this possible while still leveraging seneca or Redis? Is there a particular message format being passed over Redis which is javascript-specific (e.g. handling callbacks) or can it be used in other services with minimal changes?

Any suggestions/thoughts would be appreciated!

Thanks,
Henry

**Comment by rjrodger** [comment]
documentation needed in any case, noting this in
https://github.com/rjrodger/seneca/issues/93
