### ISSUE TITLE
seneca.util.deepextend can not handle Buffers

### ISSUE THREAD

**Issue by ErikOrjehag** [rjrodger/seneca#86]
I was storing my ssl-cert in a Buffer (returned from fs.readFileSync) attached to my https options object. When I tried to use seneca.util.deepextend() the Buffer got converted to a strange Array-object and was causing me a lot of problems.

```js
var options = seneca.util.deepextend({
  str: "hello world"
},
{
  buff: new Buffer("foo bar"),
  str: "HELLO!!"
});

console.log(options); // prints { str: 'HELLO!!', buff: <Object 66 6f 6f 20 62 61 72> }
```
Notice that options.buff isnt a Buffer any more!
```js
console.log(JSON.stringify(options.buff)); //prints [102,111,111,32,98,97,114]
```
My workaround so far has been to call
```js
var cert = fs.readFileSync("cert.pem").toString();
```
which works but I still think that deepextend should support Buffers since it already supports Array, Date, function and RegExp objects.

My guess is that this line needs an additional check to see if "v" is a Buffer.
https://github.com/rjrodger/seneca/blob/master/lib/common.js#L196

**Comment by rjrodger** [comment]
fixed in 0.6.0 branch!
