### ISSUE TITLE
seneca overwrites params passed to seneca.act

### ISSUE THREAD

**Issue by paolochiodi** [rjrodger/seneca#88]
```js
    var attrs = {
      name: 'test'
    };

    seneca.act({role: 'test_role', cmd: 'test_cmd'}, attrs, function(err, result) {
      console.log(attrs) // => { name: 'test', role: 'test_role', cmd: 'test_cmd' }
    })

```

While not a big problem is a bit unexpected and trick newcomers.  
Also dangerous when reusing the initial attributes, e.g.:

```js
    var attrs = {
      name: 'test'
    };

    seneca.act({role: 'test_role', cmd: 'get'}, attrs, function(err, result) {
      if (result) {
        return done(null, result)
      }

      console.log(attrs) // => { name: 'test', role: 'test_role', cmd: 'get' }

      seneca.act({role: 'test_role', cmd: 'create'}, attrs, done); //=> actually executes the "get" cmd and enter infinite loop because attrs overwrites the first param
    })

```

**Comment by rjrodger** [comment]
yeah, needs to be documented
it is the desired behaviour, the normal case being a string to define the action pattern, followed by some params: seneca.act("foo:a,bar:b",params)
it's mostly just for convenience, hence it also supports an object as the first param
converting this issue to a documentation one :)

**Comment by paolochiodi** [comment]
Still sounds a bit weird to me that seneca overwrites my attrs/params object.

**Comment by rjrodger** [comment]
this was the original reason: https://github.com/rjrodger/seneca/issues/65

overriding is deliberate here because if you see:
`seneca.act( "foo:a", params )`
in your code, you *definitely* want foo == "a", no matter what is in params

**Comment by paolochiodi** [comment]
I understand this, but I'm be surprised to find attribute "foo" in my params object.

To me is perfectly correct the current order of precedence, what is misleading is that "params" got changed inside seneca.act.
I'd just replace https://github.com/rjrodger/seneca/blob/master/lib/seneca.js#L1459 with
```js
    return _.extend(
        args,
        { pattern: _.extend(
          {}
// Precedence of arguments in add,act is left-to-right
          args.moreobjargs ? args.moreobjargs : {},
          args.objargs ? args.objargs : {},
          args.strargs ? jsonic( args.strargs ) : {},
          fixed || {} )
        })
```

notice the additional empty object `{}` at the beginning of the extend chain

**Comment by rjrodger** [comment]
ah - yes! I understand :)
will fix this

**Comment by paolochiodi** [comment]
:+1:
